### ISSUE TITLE
Count a base  only once for overlapping mates 

### ISSUE THREAD

**Issue by melferink** [lomereiter/sambamba#204]
Hi Artem,

I've noticed that DEPTH does not take overlapping bases in mates into account when counting.
With overlapping mates I mean a forward and a reverse read coming from the same DNA molecule, thus in principe the same base is sequenced twice (but in opposite direction). DEPTH also counts these bases twice in the results.

Mpileup (I think v1.1 and higher) and GATK HC will merge (or exclude the overlap in 1 mate i guess) in their calculations.  

Is this something you can include in DEPTH as an additional option?

Greetz,
Martin

**Comment by lomereiter** [comment]
Hi Martin,

Thanks for the suggestion, I haven't considered this situation.

It's definitely possible, I see a simple and fast solution:
* compute hashes of read names
* for each pileup column:
  * sort (hash, index) pairs by hash to find potential mates
  * if any are found, check their read names as well, and exclude the mate with lower base quality (not sure what to do if either hits an indel, perhaps simply compare mapping quality then)

Expect to see it included by next week.

**Comment by melferink** [comment]
Great, thanks!

One small remark: please don't exclude the entire mate, only the overlapping bases.

**Comment by lomereiter** [comment]
Hi Martin,

I'm more or less sure `depth base` now works as expected with `--fix-mate-overlaps` option.
Combining overlapping mate handling with read counting logic in `region` subcommand proved a lot more complicated, but I have a faint hope that I fixed most bugs :)

I've put a small `.bam` into `test/data`, which contains pretty much _only_ overlapping mates, with coverage up to 100 in some places. It would be helpful if you checked some random small regions just manually and confirmed that everything is counted correctly, or reported (sets of) regions where things went wrong.

I presume that you can build the tool by yourself, I've just updated compilation instructions in the readme.

**Comment by melferink** [comment]
Hi Artem,

I did some testing and on first sight it looks ok (overlapping bases are indeed not taken into account).
However, I see a different problem/bug which I cannot explain. See below for the commands/output.
In this case I calculated the 15X for region  2:166868600-166868813.
First without the -m option, second with -m.
For the first 15X% is 89.7196%, the second 91.5888%. 
This is strange, because I would expect the 15% to be equal or lower, not higher (bases should  only be removed with the -m  option, not added).
I also looked with depth base, and for both with and without -m I counted 192 bases >=15X  ( 192/214= 89.7196%). Both therefore should be 89.7196%, but only without -m is.
Thus, depth base calculates 192 bases >15X, and depth region 196 bases (196/214=  91.5888%).

Any idea what causes the 4bp differences (could it be an offset difference)? 

Thanks again!
(p.s. if you need a BAM slice, let me know!)


[melferink@hpcs04 160330_NB501039_0019_AHWNWYBGXX]$ ../sambamba depth region 12878/mapping/12878_dedup.realigned.bam -q 10 -F " mapping_quality >= 20 and not duplicate and not failed_quality_control and not secondary_alignment " -L 2:166868600-166868813  -T 15 
# chrom chromStart      chromEnd        readCount       meanCoverage    percentage15    sampleName
Processing reference #2 (2)
2       166868599       166868813       41      20.2196 89.7196 12878

[melferink@hpcs04 160330_NB501039_0019_AHWNWYBGXX]$ ../sambamba depth region 12878/mapping/12878_dedup.realigned.bam -q 10 -F " mapping_quality >= 20 and not duplicate and not failed_quality_control and not secondary_alignment " -L 2:166868600-166868813  -T 15 -m
# chrom chromStart      chromEnd        readCount       meanCoverage    percentage15    sampleName
Processing reference #2 (2)
2       166868599       166868813       29      17.8084 91.5888 12878

**Comment by lomereiter** [comment]
Hi Martin,

That must be a bug. Please slice a region of 5-10kbp around the place an attach the file (check that the difference is still present).

**Comment by melferink** [comment]
[12878_dedup.realigned_slice.bam.gz](https://github.com/lomereiter/sambamba/files/229769/12878_dedup.realigned_slice.bam.gz)

Hope this works (bgzipped for uploading purposes)

The difference was still present.

Greets,
Martin

**Comment by lomereiter** [comment]
Thanks, I fixed it and added your file to tests, with three different thresholds. Feel free to reopen the issue if you find any further inadequacies.
